## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('applications', ['internet', 'config-store','stats'])
    module.source = [
        'model/bulk-send-application.cc',
        'model/onoff-application.cc',
        'model/packet-sink.cc',
        'model/udp-client.cc',
        'model/udp-server.cc',
        'model/seq-ts-header.cc',
        'model/seq-ts-size-header.cc',
        'model/seq-ts-echo-header.cc',
        'model/udp-trace-client.cc',
        'model/packet-loss-counter.cc',
        'model/udp-echo-client.cc',
        'model/udp-echo-server.cc',
        'model/application-packet-probe.cc',
        'model/three-gpp-http-client.cc',
        'model/three-gpp-http-server.cc',
        'model/three-gpp-http-header.cc',
        'model/three-gpp-http-variables.cc', 
        'model/probe-listener.cc',
        'model/pscheduler.cc',
        'model/probe-sender.cc',
        'model/probe-app-2.cc',
        'model/gtcp-server.cc',
        'model/gtcp-client.cc',
        'model/query-header.cc',
        'model/query-response.cc',
        'model/query-value.cc',
        'model/scheduler-store.cc',
        'model/scheduler-topo.cc',
        'model/f-application.cc',
        'model/sim-server.cc',
        'model/bulk-send-application-2.cc',
        'model/data-transfer-header.cc',
        'helper/gtcp-helper.cc',
        'helper/bulk-send-helper.cc',
        'helper/on-off-helper.cc',
        'helper/packet-sink-helper.cc',
        'helper/udp-client-server-helper.cc',
        'helper/udp-echo-helper.cc',
        'helper/three-gpp-http-helper.cc',
        'helper/probe-helper.cc',
        'helper/probev2helper.cc',
        'helper/f-helper.cc',
        'helper/bulk-send-helper-2.cc',
        ]

    applications_test = bld.create_ns3_module_test_library('applications')
    applications_test.source = [
        'test/three-gpp-http-client-server-test.cc', 
        'test/bulk-send-application-test-suite.cc',
        'test/udp-client-server-test.cc'
        ]

    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        applications_test.source.extend([
        #   'test/applications-examples-test-suite.cc',
            ])
    
    headers = bld(features='ns3header')
    headers.module = 'applications'
    headers.source = [
        'model/bulk-send-application.h',
        'model/onoff-application.h',
        'model/packet-sink.h',
        'model/udp-client.h',
        'model/udp-server.h',
        'model/seq-ts-header.h',
        'model/seq-ts-size-header.h',
        'model/seq-ts-echo-header.h',
        'model/udp-trace-client.h',
        'model/packet-loss-counter.h',
        'model/udp-echo-client.h',
        'model/udp-echo-server.h',
        'model/application-packet-probe.h',
        'model/three-gpp-http-client.h',
        'model/three-gpp-http-server.h',
        'model/three-gpp-http-header.h',
        'model/three-gpp-http-variables.h',
        'model/probe-listener.h',
        'model/pscheduler.h',
        'model/probe-sender.h',
        'model/probe-app-2.h',
        'model/gtcp-server.h',
        'model/gtcp-client.h',
        'model/query-value.h',
        'model/scheduler-store.h',
        'helper/gtcp-helper.h',
        'model/query-header.h',
        'model/query-response.h',
        'model/scheduler-topo.h',
        'model/f-application.h',
        'model/sim-server.h',
        'model/bulk-send-application-2.h',
        'model/data-transfer-header.h',
        'helper/bulk-send-helper.h',
        'helper/on-off-helper.h',
        'helper/packet-sink-helper.h',
        'helper/udp-client-server-helper.h',
        'helper/udp-echo-helper.h',
        'helper/three-gpp-http-helper.h',
        'helper/probe-helper.h',
        'helper/probev2helper.h',
        'helper/f-helper.h',
        'helper/bulk-send-helper-2.h',
        ]
    
    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

    bld.ns3_python_bindings()